### PR TITLE
Migrate to Swift 3.

### PR DESCRIPTION
**Pull request by stellakovalchuk**
Hi!

Thanks for your lib! I've migrated it to Swift 3 to be able to use in Xcode 8.

Stella

### CODE REVIEW

**Comment by odrobnik** [comment]
Please change this line to `xcode8` so that we may see the unit tests pass: https://github.com/Cocoanetics/Kvitto/blob/develop/.travis.yml#L3

**Comment by odrobnik** [comment]
Also: I see a few NSString there... they could be String instead, right?

**Comment by odrobnik** [comment]
@stellakovalchuk And now we see that the unit tests also need to be updated to Swift 3....

**Comment by odrobnik** [comment]
@stellakovalchuk please do the Swift 3 migration also on the unit tests.

**Comment by odrobnik** [comment]
@stellakovalchuk running the tests manually on my machine worked, so I merged it manually. Travis seems to have some severe issues at the moment.

**Comment by stellakovalchuk** [comment]
thanks!

**Pull request merged**
